# Generated by Django 4.1.7 on 2023-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('NW', 'Новости'), ('AR', 'Статьи')], default='AR', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
